import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Adds CRM-only operational columns to `properties` and `property_details`.
 * All columns are NULL-able so the migration is safe on existing rows.
 * Consumed by the CRM properties module via the site admin properties API.
 */
export class AddCrmOnlyPropertyFields1781600000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE \`properties\`
        ADD COLUMN \`alternate_name\` varchar(255) NULL,
        ADD COLUMN \`alternate_phone\` varchar(50) NULL,
        ADD COLUMN \`alternate_email\` varchar(255) NULL,
        ADD COLUMN \`transaction_type\` varchar(100) NULL,
        ADD COLUMN \`handover_date\` varchar(100) NULL,
        ADD COLUMN \`road_name\` varchar(255) NULL,
        ADD COLUMN \`road_access\` varchar(100) NULL,
        ADD COLUMN \`tenant_occupied\` varchar(100) NULL,
        ADD COLUMN \`sale_type\` varchar(50) NULL,
        ADD COLUMN \`agent_name\` varchar(255) NULL,
        ADD COLUMN \`agency_name\` varchar(255) NULL,
        ADD COLUMN \`commission_terms\` varchar(255) NULL,
        ADD COLUMN \`expected_sale_price\` decimal(12,2) NULL,
        ADD COLUMN \`monthly_rent\` decimal(12,2) NULL,
        ADD COLUMN \`lock_in_period\` varchar(100) NULL,
        ADD COLUMN \`taxes\` varchar(255) NULL,
        ADD COLUMN \`registration_charge\` varchar(255) NULL,
        ADD COLUMN \`mode_of_payment\` varchar(255) NULL,
        ADD COLUMN \`time_for_registration\` varchar(100) NULL,
        ADD COLUMN \`remark\` text NULL,
        ADD COLUMN \`demand_area\` varchar(100) NULL,
        ADD COLUMN \`rental_yield\` varchar(100) NULL,
        ADD COLUMN \`comparative_price\` varchar(100) NULL,
        ADD COLUMN \`market_price\` varchar(100) NULL,
        ADD COLUMN \`ownership_title_verified\` varchar(50) NULL,
        ADD COLUMN \`encumbrance_certificate\` varchar(50) NULL,
        ADD COLUMN \`rental_agreement_draft\` varchar(50) NULL,
        ADD COLUMN \`tslr_fmb\` varchar(50) NULL,
        ADD COLUMN \`tax_receipt\` varchar(50) NULL,
        ADD COLUMN \`eb_receipt\` varchar(50) NULL,
        ADD COLUMN \`patta_chitta\` varchar(50) NULL,
        ADD COLUMN \`approvals\` varchar(255) NULL,
        ADD COLUMN \`finance_facing\` varchar(50) NULL,
        ADD COLUMN \`hypothecation\` varchar(50) NULL,
        ADD COLUMN \`deviation\` varchar(50) NULL,
        ADD COLUMN \`attachment1\` varchar(1024) NULL,
        ADD COLUMN \`attachment2\` varchar(1024) NULL,
        ADD COLUMN \`attachment3\` varchar(1024) NULL,
        ADD COLUMN \`attachment4\` varchar(1024) NULL,
        ADD COLUMN \`attachment5\` varchar(1024) NULL,
        ADD COLUMN \`attachment6\` varchar(1024) NULL
    `);

    await queryRunner.query(`
      ALTER TABLE \`property_details\`
        ADD COLUMN \`uds_area\` decimal(12,2) NULL,
        ADD COLUMN \`unit_number\` varchar(100) NULL,
        ADD COLUMN \`unit_type\` varchar(50) NULL,
        ADD COLUMN \`number_of_flats\` int NULL,
        ADD COLUMN \`tower_nos\` int NULL,
        ADD COLUMN \`pooja_room\` tinyint(1) NULL,
        ADD COLUMN \`study_room\` tinyint(1) NULL,
        ADD COLUMN \`architectural_style\` varchar(100) NULL,
        ADD COLUMN \`available_portion\` varchar(50) NULL,
        ADD COLUMN \`amenities\` text NULL,
        ADD COLUMN \`plot_nos\` int NULL,
        ADD COLUMN \`zoning\` varchar(255) NULL,
        ADD COLUMN \`plot_type\` varchar(100) NULL,
        ADD COLUMN \`land_type\` varchar(100) NULL,
        ADD COLUMN \`topography\` varchar(255) NULL,
        ADD COLUMN \`soil_type\` varchar(255) NULL,
        ADD COLUMN \`irrigation\` varchar(255) NULL,
        ADD COLUMN \`fencing\` varchar(255) NULL,
        ADD COLUMN \`crop_suitability\` varchar(255) NULL,
        ADD COLUMN \`existing_plantation\` varchar(255) NULL,
        ADD COLUMN \`bore_well\` tinyint(1) NULL,
        ADD COLUMN \`storage_tank\` tinyint(1) NULL,
        ADD COLUMN \`water_sources\` varchar(255) NULL,
        ADD COLUMN \`sf_number\` varchar(255) NULL,
        ADD COLUMN \`property_use\` varchar(255) NULL,
        ADD COLUMN \`no_of_lifts\` int NULL,
        ADD COLUMN \`dimension\` varchar(255) NULL,
        ADD COLUMN \`frontage\` varchar(100) NULL,
        ADD COLUMN \`outside_parking\` tinyint(1) NULL,
        ADD COLUMN \`visitors_parking\` varchar(100) NULL,
        ADD COLUMN \`fire_safety\` tinyint(1) NULL,
        ADD COLUMN \`electricity_connection\` varchar(255) NULL,
        ADD COLUMN \`conference_room\` int NULL,
        ADD COLUMN \`seater\` int NULL,
        ADD COLUMN \`tenant_mix\` varchar(255) NULL,
        ADD COLUMN \`building_type\` varchar(100) NULL,
        ADD COLUMN \`number_of_bays\` int NULL,
        ADD COLUMN \`number_of_cabins\` int NULL,
        ADD COLUMN \`loading_bays\` int NULL,
        ADD COLUMN \`warehouse_racks\` int NULL,
        ADD COLUMN \`truck_trailer_access\` tinyint(1) NULL,
        ADD COLUMN \`crane_available\` tinyint(1) NULL,
        ADD COLUMN \`worker_facilities\` text NULL,
        ADD COLUMN \`nearest_highway\` varchar(255) NULL,
        ADD COLUMN \`nearest_railway\` varchar(255) NULL,
        ADD COLUMN \`nearest_port\` varchar(255) NULL,
        ADD COLUMN \`nearest_airport\` varchar(255) NULL,
        ADD COLUMN \`labour_availability\` varchar(255) NULL,
        ADD COLUMN \`advance_rent\` decimal(12,2) NULL,
        ADD COLUMN \`lease_term\` varchar(100) NULL,
        ADD COLUMN \`incremental_rent\` varchar(100) NULL,
        ADD COLUMN \`electricity_charges\` varchar(100) NULL,
        ADD COLUMN \`high_speed_wifi\` tinyint(1) NULL,
        ADD COLUMN \`air_conditioning\` tinyint(1) NULL,
        ADD COLUMN \`cctv_surveillance\` tinyint(1) NULL,
        ADD COLUMN \`elevator_access\` tinyint(1) NULL,
        ADD COLUMN \`security_staff\` tinyint(1) NULL,
        ADD COLUMN \`furniture_provided\` text NULL,
        ADD COLUMN \`outdoor_spaces\` text NULL,
        ADD COLUMN \`utilities_provided\` text NULL,
        ADD COLUMN \`neighborhood_highlights\` text NULL,
        ADD COLUMN \`community_facilities\` text NULL,
        ADD COLUMN \`accessibility\` text NULL,
        ADD COLUMN \`furnishing_status\` varchar(50) NULL
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE \`property_details\`
        DROP COLUMN \`furnishing_status\`,
        DROP COLUMN \`accessibility\`,
        DROP COLUMN \`community_facilities\`,
        DROP COLUMN \`neighborhood_highlights\`,
        DROP COLUMN \`utilities_provided\`,
        DROP COLUMN \`outdoor_spaces\`,
        DROP COLUMN \`furniture_provided\`,
        DROP COLUMN \`security_staff\`,
        DROP COLUMN \`elevator_access\`,
        DROP COLUMN \`cctv_surveillance\`,
        DROP COLUMN \`air_conditioning\`,
        DROP COLUMN \`high_speed_wifi\`,
        DROP COLUMN \`electricity_charges\`,
        DROP COLUMN \`incremental_rent\`,
        DROP COLUMN \`lease_term\`,
        DROP COLUMN \`advance_rent\`,
        DROP COLUMN \`labour_availability\`,
        DROP COLUMN \`nearest_airport\`,
        DROP COLUMN \`nearest_port\`,
        DROP COLUMN \`nearest_railway\`,
        DROP COLUMN \`nearest_highway\`,
        DROP COLUMN \`worker_facilities\`,
        DROP COLUMN \`crane_available\`,
        DROP COLUMN \`truck_trailer_access\`,
        DROP COLUMN \`warehouse_racks\`,
        DROP COLUMN \`loading_bays\`,
        DROP COLUMN \`number_of_cabins\`,
        DROP COLUMN \`number_of_bays\`,
        DROP COLUMN \`building_type\`,
        DROP COLUMN \`tenant_mix\`,
        DROP COLUMN \`seater\`,
        DROP COLUMN \`conference_room\`,
        DROP COLUMN \`electricity_connection\`,
        DROP COLUMN \`fire_safety\`,
        DROP COLUMN \`visitors_parking\`,
        DROP COLUMN \`outside_parking\`,
        DROP COLUMN \`frontage\`,
        DROP COLUMN \`dimension\`,
        DROP COLUMN \`no_of_lifts\`,
        DROP COLUMN \`property_use\`,
        DROP COLUMN \`sf_number\`,
        DROP COLUMN \`water_sources\`,
        DROP COLUMN \`storage_tank\`,
        DROP COLUMN \`bore_well\`,
        DROP COLUMN \`existing_plantation\`,
        DROP COLUMN \`crop_suitability\`,
        DROP COLUMN \`fencing\`,
        DROP COLUMN \`irrigation\`,
        DROP COLUMN \`soil_type\`,
        DROP COLUMN \`topography\`,
        DROP COLUMN \`land_type\`,
        DROP COLUMN \`plot_type\`,
        DROP COLUMN \`zoning\`,
        DROP COLUMN \`plot_nos\`,
        DROP COLUMN \`amenities\`,
        DROP COLUMN \`available_portion\`,
        DROP COLUMN \`architectural_style\`,
        DROP COLUMN \`study_room\`,
        DROP COLUMN \`pooja_room\`,
        DROP COLUMN \`tower_nos\`,
        DROP COLUMN \`number_of_flats\`,
        DROP COLUMN \`unit_type\`,
        DROP COLUMN \`unit_number\`,
        DROP COLUMN \`uds_area\`
    `);

    await queryRunner.query(`
      ALTER TABLE \`properties\`
        DROP COLUMN \`attachment6\`,
        DROP COLUMN \`attachment5\`,
        DROP COLUMN \`attachment4\`,
        DROP COLUMN \`attachment3\`,
        DROP COLUMN \`attachment2\`,
        DROP COLUMN \`attachment1\`,
        DROP COLUMN \`deviation\`,
        DROP COLUMN \`hypothecation\`,
        DROP COLUMN \`finance_facing\`,
        DROP COLUMN \`approvals\`,
        DROP COLUMN \`patta_chitta\`,
        DROP COLUMN \`eb_receipt\`,
        DROP COLUMN \`tax_receipt\`,
        DROP COLUMN \`tslr_fmb\`,
        DROP COLUMN \`rental_agreement_draft\`,
        DROP COLUMN \`encumbrance_certificate\`,
        DROP COLUMN \`ownership_title_verified\`,
        DROP COLUMN \`market_price\`,
        DROP COLUMN \`comparative_price\`,
        DROP COLUMN \`rental_yield\`,
        DROP COLUMN \`demand_area\`,
        DROP COLUMN \`remark\`,
        DROP COLUMN \`time_for_registration\`,
        DROP COLUMN \`mode_of_payment\`,
        DROP COLUMN \`registration_charge\`,
        DROP COLUMN \`taxes\`,
        DROP COLUMN \`lock_in_period\`,
        DROP COLUMN \`monthly_rent\`,
        DROP COLUMN \`expected_sale_price\`,
        DROP COLUMN \`commission_terms\`,
        DROP COLUMN \`agency_name\`,
        DROP COLUMN \`agent_name\`,
        DROP COLUMN \`sale_type\`,
        DROP COLUMN \`tenant_occupied\`,
        DROP COLUMN \`road_access\`,
        DROP COLUMN \`road_name\`,
        DROP COLUMN \`handover_date\`,
        DROP COLUMN \`transaction_type\`,
        DROP COLUMN \`alternate_email\`,
        DROP COLUMN \`alternate_phone\`,
        DROP COLUMN \`alternate_name\`
    `);
  }
}
